# Generated by Django 5.2.11 on 2026-02-10 22:36

from django.db import migrations


def populate_default_stages(apps, schema_editor):
    PipelineStage = apps.get_model('leads', 'PipelineStage')

    default_stages = [
        {'name': 'New', 'key': 'new', 'description': 'Initial stage', 'order': 1},
        {'name': 'Attempted to Contact', 'key': 'attempted', 'description': 'Outreach begun', 'order': 2},
        {'name': 'Contacted', 'key': 'contacted', 'description': 'Conversation established', 'order': 3},
        {'name': 'Unqualified', 'key': 'unqualified', 'description': 'Does not meet criteria', 'order': 4},
        {'name': 'Nurturing', 'key': 'nurturing', 'description': 'Warm but not ready', 'order': 5},
        {'name': 'Converted', 'key': 'converted', 'description': 'Successfully closed', 'order': 6},
    ]

    for stage_data in default_stages:
        PipelineStage.objects.get_or_create(key=stage_data['key'], defaults=stage_data)


def reverse_populate(apps, schema_editor):
    PipelineStage = apps.get_model('leads', 'PipelineStage')
    PipelineStage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_pipelinestage'),
    ]

    operations = [
        migrations.RunPython(populate_default_stages, reverse_populate),
    ]
