# Generated by Django 5.2.11 on 2026-02-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadactivity_leadnote_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID for direct messaging', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (without @)', max_length=100),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('status_change', 'Status Changed'), ('note_added', 'Note Added'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('telegram_sent', 'Telegram Message Sent'), ('telegram_received', 'Telegram Message Received')], max_length=50),
        ),
    ]
