# Generated by Django 5.2.11 on 2026-02-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_telegram_chat_id_lead_telegram_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestage',
            options={'ordering': ['segment', 'order', 'id'], 'verbose_name': 'Pipeline Stage', 'verbose_name_plural': 'Pipeline Stages'},
        ),
        migrations.AddField(
            model_name='lead',
            name='segment',
            field=models.CharField(choices=[('usa', 'USA'), ('china', 'China')], default='usa', max_length=20),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='segment',
            field=models.CharField(choices=[('usa', 'USA'), ('china', 'China')], default='usa', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('key', 'segment')},
        ),
    ]
