# Generated by Django 5.2.11 on 2026-02-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_pipelinestage_options_lead_segment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255)),
                ('bot_username', models.CharField(max_length=255)),
                ('bot_first_name', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Configuration',
                'verbose_name_plural': 'Telegram Configuration',
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='segment',
            field=models.CharField(choices=[('usa', 'Segment A'), ('china', 'Segment B')], default='usa', max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='segment',
            field=models.CharField(choices=[('usa', 'Segment A'), ('china', 'Segment B')], default='usa', max_length=20),
        ),
    ]
