# Generated by Django 5.2.11 on 2026-02-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_telegramconfig_alter_lead_segment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='instagram_user_id',
            field=models.CharField(blank=True, help_text='Instagram user ID', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='telegram_user_id',
            field=models.CharField(blank=True, help_text='Telegram user ID (unique identifier)', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='WhatsApp phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
