# Generated by Django 5.2.11 on 2026-02-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_instagram_user_id_lead_instagram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, help_text='Street address', max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign_source',
            field=models.CharField(blank=True, help_text='Marketing campaign', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='competitor',
            field=models.CharField(blank=True, help_text='Which competitor they chose', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='do_not_contact',
            field=models.BooleanField(default=False, help_text='Opted out of communication'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_bounced',
            field=models.BooleanField(default=False, help_text='Email is invalid/bounced'),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateField(blank=True, help_text='Projected conversion date', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='job_title',
            field=models.CharField(blank=True, help_text="Contact's job title/position", max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='language',
            field=models.CharField(blank=True, help_text='Preferred language', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, help_text="Why they didn't convert", max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='mobile_phone',
            field=models.CharField(blank=True, help_text='Mobile phone number', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_date',
            field=models.DateField(blank=True, help_text='Scheduled next action', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='office_phone',
            field=models.CharField(blank=True, help_text='Office/direct line', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='postal_code',
            field=models.CharField(blank=True, help_text='ZIP or Postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_contact_method',
            field=models.CharField(blank=True, help_text='Email, Phone, Telegram, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_contact_time',
            field=models.CharField(blank=True, help_text='Best time to reach them', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Who referred them', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='secondary_email',
            field=models.EmailField(blank=True, help_text='Alternative email address', max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='state_province',
            field=models.CharField(blank=True, help_text='State or Province', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='timezone',
            field=models.CharField(blank=True, help_text='Timezone for scheduling', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, help_text='When they opted out', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True, help_text='Company website'),
        ),
    ]
