# Generated by Django 5.2.11 on 2026-02-11 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_address_lead_campaign_source_lead_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_auto_response', models.BooleanField(default=False, help_text='Enable AI auto-response for Telegram messages')),
                ('auto_extract_data', models.BooleanField(default=False, help_text='Automatically extract lead data from conversations')),
                ('use_knowledge_base', models.BooleanField(default=False, help_text='Use RAG/knowledge base for responses')),
                ('response_delay', models.IntegerField(default=5, help_text='Delay before sending response (seconds)')),
                ('system_prompt', models.TextField(blank=True, default='You are a helpful assistant representing this company. Be professional, friendly, and helpful.', help_text='Define AI personality and behavior')),
                ('automatic_followups', models.BooleanField(default=False, help_text='Enable automatic follow-up messages')),
                ('auto_schedule_on_incomplete', models.BooleanField(default=False, help_text='Auto-schedule if conversation incomplete')),
                ('days_until_first_followup', models.IntegerField(default=3, help_text='Days to wait before first follow-up')),
                ('days_between_followups', models.IntegerField(default=7, help_text='Days between subsequent follow-ups')),
                ('maximum_followups', models.IntegerField(default=3, help_text='Maximum number of follow-up attempts')),
                ('followup_message_template', models.TextField(blank=True, default='Hi {contact_person}, just following up on our previous conversation. Are you still interested?', help_text='Template for follow-up messages (use {company_name}, {contact_person} variables)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configuration',
            },
        ),
    ]
