# Generated by Django 5.2.11 on 2026-02-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_aiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='knowledge_docs/')),
                ('file_type', models.CharField(help_text='File extension (pdf, docx, txt)', max_length=50)),
                ('extracted_text', models.TextField(blank=True, help_text='Extracted text content from document')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for similarity search', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Include in AI responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Document',
                'verbose_name_plural': 'Knowledge Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Knowledge content (FAQ, policy, etc.)')),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for similarity search', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Include in AI responses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Entry',
                'verbose_name_plural': 'Knowledge Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
