# Generated by Django 5.2.11 on 2026-02-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_alter_aiconfig_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='company_profile',
            field=models.TextField(blank=True, default='**The Grand Meridian Hotel** - A Five-Star Luxury Experience\n\nWe are a prestigious five-star hotel offering world-class hospitality in the heart of the city. Our property features:\n\n**Accommodations:**\n- 250 elegantly appointed guest rooms and suites\n- Panoramic city and ocean views\n- Premium amenities including marble bathrooms, king-size beds, and smart room technology\n- 24/7 concierge and room service\n\n**Facilities:**\n- Award-winning fine dining restaurant and rooftop bar\n- Full-service spa and wellness center with indoor pool\n- State-of-the-art fitness center open 24/7\n- Executive business center and meeting rooms\n- Valet parking and airport shuttle service\n\n**Services:**\n- Personalized guest services and event planning\n- Wedding and conference facilities for up to 500 guests\n- In-room dining featuring local and international cuisine\n- Multilingual staff available around the clock\n\n**Pricing:** Rooms start at $350/night for standard rooms, with suites ranging from $800-2,500/night. Special packages and corporate rates available.\n\n**Target Guests:** Business travelers, luxury tourists, wedding parties, and conference attendees seeking exceptional service and premium accommodations.', help_text='Company information and context for AI responses'),
        ),
    ]
