# Generated by Django 5.2.11 on 2026-02-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_aiconfig_system_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Facebook Page Access Token', max_length=500)),
                ('page_id', models.CharField(help_text='Facebook Page ID', max_length=100)),
                ('instagram_business_account_id', models.CharField(help_text='Instagram Business Account ID', max_length=100)),
                ('username', models.CharField(help_text='Instagram username', max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Configuration',
                'verbose_name_plural': 'Instagram Configuration',
            },
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('status_change', 'Status Changed'), ('note_added', 'Note Added'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('telegram_sent', 'Telegram Message Sent'), ('telegram_received', 'Telegram Message Received'), ('instagram_sent', 'Instagram Message Sent'), ('instagram_received', 'Instagram Message Received')], max_length=50),
        ),
    ]
