# Generated by Django 5.2.11 on 2026-02-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_instagramconfig_alter_leadactivity_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('attempted', 'Attempted to Contact / Working'), ('contacted', 'Contacted / Connected'), ('unqualified', 'Unqualified / Disqualified'), ('nurturing', 'Nurturing / Pending'), ('converted', 'Converted')], help_text='Lead status this template applies to', max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether to send follow-up when lead enters this status')),
                ('message_template', models.TextField(blank=True, help_text='Message template with {contact_person}, {company_name} variables')),
                ('delay_minutes', models.IntegerField(default=0, help_text='Delay before sending (0 = immediate)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Follow-Up Template',
                'verbose_name_plural': 'Follow-Up Templates',
                'ordering': ['status'],
            },
        ),
    ]
