# Generated by Django 5.2.11 on 2026-02-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_followuptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestage',
            name='followup_enabled',
            field=models.BooleanField(default=False, help_text='Send follow-up message when lead enters this stage'),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='followup_message_template',
            field=models.TextField(blank=True, help_text='Message template with {contact_person}, {company_name} variables'),
        ),
    ]
