# Generated by Django 5.2.11 on 2026-02-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_pipelinestage_followup_enabled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUpTemplate',
        ),
    ]
