# Generated by Django 5.2.11 on 2026-02-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_delete_followuptemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconfig',
            name='auto_schedule_on_incomplete',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='automatic_followups',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='days_between_followups',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='days_until_first_followup',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='followup_message_template',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='maximum_followups',
        ),
        migrations.RemoveField(
            model_name='pipelinestage',
            name='followup_enabled',
        ),
        migrations.RemoveField(
            model_name='pipelinestage',
            name='followup_message_template',
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='check_frequency_hours',
            field=models.IntegerField(default=24, help_text='How often to check leads (hours)'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='inactivity_threshold_days',
            field=models.IntegerField(default=2, help_text='Days of inactivity before follow-up'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='max_followup_attempts',
            field=models.IntegerField(default=3, help_text='Maximum follow-up attempts per lead'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='proactive_outreach_enabled',
            field=models.BooleanField(default=False, help_text='Enable autonomous AI follow-ups'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_followup_count',
            field=models.IntegerField(default=0, help_text='Number of AI-initiated follow-ups sent'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_ai_followup_at',
            field=models.DateTimeField(blank=True, help_text='Last AI follow-up timestamp', null=True),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Final stage - AI agent will not follow up on leads in this stage'),
        ),
    ]
