# Generated by Django 5.2.11 on 2026-02-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_remove_aiconfig_auto_schedule_on_incomplete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='WhatsApp Cloud API Access Token', max_length=500)),
                ('phone_number_id', models.CharField(help_text='WhatsApp Business Phone Number ID', max_length=100)),
                ('display_phone_number', models.CharField(blank=True, help_text='Display phone number', max_length=50)),
                ('verified_name', models.CharField(blank=True, help_text='Verified business name', max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
            },
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('status_change', 'Status Changed'), ('note_added', 'Note Added'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('telegram_sent', 'Telegram Message Sent'), ('telegram_received', 'Telegram Message Received'), ('instagram_sent', 'Instagram Message Sent'), ('instagram_received', 'Instagram Message Received'), ('whatsapp_sent', 'WhatsApp Message Sent'), ('whatsapp_received', 'WhatsApp Message Received')], max_length=50),
        ),
    ]
