# Generated by Django 5.2.11 on 2026-02-16 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_whatsappconfig_alter_leadactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='auto_execute_tasks',
            field=models.BooleanField(default=False, help_text='AI creates and completes tasks autonomously'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='auto_status_progression',
            field=models.BooleanField(default=False, help_text='AI automatically moves leads through pipeline stages'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='conversation_goals_enabled',
            field=models.BooleanField(default=False, help_text='AI tracks and pursues conversation goals'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='smart_objection_handling',
            field=models.BooleanField(default=False, help_text='AI detects and handles objections automatically'),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_objection',
            field=models.CharField(blank=True, choices=[('price', 'Price/Budget'), ('timing', 'Timing/Not Ready'), ('competitor', 'Using Competitor'), ('authority', 'Not Decision Maker'), ('need', 'No Need'), ('other', 'Other')], help_text='Current objection type', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_objection_at',
            field=models.DateTimeField(blank=True, help_text='When last objection was detected', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='objection_count',
            field=models.IntegerField(default=0, help_text='Total objections detected'),
        ),
        migrations.AddField(
            model_name='task',
            name='executed_at',
            field=models.DateTimeField(blank=True, help_text='When AI executed this task', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_content',
            field=models.TextField(blank=True, help_text='Content to send/action to take'),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_result',
            field=models.TextField(blank=True, help_text='Result of auto-execution'),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_type',
            field=models.CharField(choices=[('send_message', 'Send Message'), ('send_document', 'Send Document'), ('update_status', 'Update Status'), ('schedule_followup', 'Schedule Follow-up'), ('none', 'Manual Task')], default='none', help_text='How to execute this task', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Was this task created by AI'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_auto_executable',
            field=models.BooleanField(default=False, help_text='Can AI execute this task automatically'),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('status_change', 'Status Changed'), ('note_added', 'Note Added'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('telegram_sent', 'Telegram Message Sent'), ('telegram_received', 'Telegram Message Received'), ('instagram_sent', 'Instagram Message Sent'), ('instagram_received', 'Instagram Message Received'), ('whatsapp_sent', 'WhatsApp Message Sent'), ('whatsapp_received', 'WhatsApp Message Received'), ('ai_status_change', 'AI Changed Status'), ('objection_detected', 'Objection Detected'), ('task_auto_completed', 'AI Completed Task'), ('goal_completed', 'Goal Achieved'), ('goal_created', 'Goal Created')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('follow_up', 'Follow Up'), ('send_info', 'Send Information'), ('send_case_study', 'Send Case Study'), ('request_meeting', 'Request Meeting'), ('send_proposal', 'Send Proposal'), ('other', 'Other')], default='follow_up', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('collect_email', 'Collect Email'), ('collect_phone', 'Collect Phone'), ('schedule_call', 'Schedule Call'), ('schedule_meeting', 'Schedule Meeting'), ('send_proposal', 'Send Proposal'), ('send_info', 'Send Information'), ('handle_objection', 'Handle Objection'), ('close_deal', 'Close Deal'), ('qualify_lead', 'Qualify Lead'), ('get_decision_maker', 'Get Decision Maker')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('description', models.TextField(blank=True, help_text='Additional context for this goal')),
                ('target_value', models.CharField(blank=True, help_text='Target value to collect (e.g., specific info needed)', max_length=255)),
                ('achieved_value', models.CharField(blank=True, help_text='Value collected when goal achieved', max_length=255)),
                ('attempts', models.IntegerField(default=0, help_text='Number of attempts made toward this goal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Was this goal created by AI')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Lead Goal',
                'verbose_name_plural': 'Lead Goals',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
