# Generated by Django 5.2.11 on 2026-02-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_aiconfig_auto_execute_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='instagram_user_id',
            field=models.CharField(blank=True, help_text='Instagram user ID', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='instagram_username',
            field=models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.CharField(choices=[('usa', 'Segment A'), ('china', 'Segment B')], default='usa', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, help_text='Where the customer came from', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID for direct messaging', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_phone',
            field=models.CharField(blank=True, help_text='WhatsApp phone number', max_length=50),
        ),
    ]
