# Generated by Django 5.2.11 on 2026-02-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_customer_contract_end_date_customer_customer_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contract_end_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contract_start_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contract_value',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
