# Generated by Django 5.2.11 on 2026-02-23 20:25

from django.db import migrations, models


def seed_segments_and_deduplicate_stages(apps, schema_editor):
    Segment = apps.get_model('leads', 'Segment')
    PipelineStage = apps.get_model('leads', 'PipelineStage')

    # Create default segments
    Segment.objects.get_or_create(key='individual', defaults={'name': 'Individual', 'order': 0})
    Segment.objects.get_or_create(key='business', defaults={'name': 'Business', 'order': 1})

    # Deduplicate pipeline stages - keep the first one per key (lowest id)
    seen_keys = set()
    for stage in PipelineStage.objects.all().order_by('id'):
        if stage.key in seen_keys:
            stage.delete()
        else:
            seen_keys.add(stage.key)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_lead_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pipelinestage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Pipeline Stage', 'verbose_name_plural': 'Pipeline Stages'},
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='segment',
            field=models.CharField(default='individual', help_text='Customer segment (from Segment model)', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='segment',
            field=models.CharField(default='individual', help_text='Lead segment (from Segment model)', max_length=50),
        ),
        # Seed segments and deduplicate stages BEFORE making key unique
        migrations.RunPython(seed_segments_and_deduplicate_stages, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pipelinestage',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='pipelinestage',
            name='segment',
        ),
    ]
