# Generated by Django 5.2.11 on 2026-02-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_decouple_stages_from_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='complexity_score',
            field=models.IntegerField(blank=True, choices=[(1, '1 – Simple'), (2, '2 – Moderate'), (3, '3 – Complex'), (4, '4 – Very Complex'), (5, '5 – Highly Complex')], help_text='Case complexity score 1-5', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='problem_description',
            field=models.TextField(blank=True, help_text='Description of the client problem or case'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tax_years',
            field=models.CharField(blank=True, help_text='Tax years involved, e.g. 2021-2023', max_length=100),
        ),
    ]
