# Generated by Django 5.2.11 on 2026-02-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_lead_complexity_score_lead_problem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingCentralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='RingCentral App Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='RingCentral App Client Secret', max_length=255)),
                ('jwt_token', models.TextField(help_text='RingCentral JWT credential (long-lived)')),
                ('account_phone', models.CharField(help_text='RingCentral phone number to send from (e.g. +16465122142)', max_length=50)),
                ('extension_id', models.CharField(blank=True, default='~', help_text='Extension ID (default: ~ for primary)', max_length=50)),
                ('webhook_subscription_id', models.CharField(blank=True, help_text='Active webhook subscription ID', max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RingCentral Configuration',
                'verbose_name_plural': 'RingCentral Configuration',
            },
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('status_change', 'Status Changed'), ('note_added', 'Note Added'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('telegram_sent', 'Telegram Message Sent'), ('telegram_received', 'Telegram Message Received'), ('instagram_sent', 'Instagram Message Sent'), ('instagram_received', 'Instagram Message Received'), ('whatsapp_sent', 'WhatsApp Message Sent'), ('whatsapp_received', 'WhatsApp Message Received'), ('ringcentral_sms_sent', 'RingCentral SMS Sent'), ('ringcentral_sms_received', 'RingCentral SMS Received'), ('ringcentral_call_started', 'Phone Call Started'), ('ringcentral_call_ended', 'Phone Call Ended'), ('ringcentral_call_analyzed', 'Phone Call Analysis'), ('ai_status_change', 'AI Changed Status'), ('objection_detected', 'Objection Detected'), ('task_auto_completed', 'AI Completed Task'), ('goal_completed', 'Goal Achieved'), ('goal_created', 'Goal Created')], max_length=50),
        ),
    ]
