# Generated by Django 5.2.11 on 2026-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_nomadcamp_aiconfig_prompts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfig',
            name='company_profile',
            field=models.TextField(blank=True, default='**The Grand Meridian Hotel** - A Five-Star Luxury Experience\n\nWe are a prestigious five-star hotel offering world-class hospitality in the heart of the city. Our property features:\n\n**Accommodations:**\n- 250 elegantly appointed guest rooms and suites\n- Panoramic city and ocean views\n- Premium amenities including marble bathrooms, king-size beds, and smart room technology\n- 24/7 concierge and room service\n\n**Facilities:**\n- Award-winning fine dining restaurant and rooftop bar\n- Full-service spa and wellness center with indoor pool\n- State-of-the-art fitness center open 24/7\n- Executive business center and meeting rooms\n- Valet parking and airport shuttle service\n\n**Services:**\n- Personalized guest services and event planning\n- Wedding and conference facilities for up to 500 guests\n- In-room dining featuring local and international cuisine\n- Multilingual staff available around the clock\n\n**Pricing:** Rooms start at $350/night for standard rooms, with suites ranging from $800-2,500/night. Special packages and corporate rates available.\n\n**Target Guests:** Business travelers, luxury tourists, wedding parties, and conference attendees seeking exceptional service and premium accommodations.', help_text='Company information and context for AI responses'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a skilled sales and support agent with an "Always Be Closing" mindset. Your goals are:\n\n1. **Review Conversation History**: ALWAYS check what has already been discussed. Never ask for information the customer already provided.\n2. **Understand Customer Needs**: Ask NEW targeted questions based on what you don\'t know yet. Build on previous responses.\n3. **Build Rapport**: Be warm, professional, and genuinely helpful. Show you remember previous interactions.\n4. **Provide Value**: Share relevant information and demonstrate how our solution solves their specific problems.\n5. **Move Toward Conversion**: Guide every conversation toward the next step - booking, quote, demo, or purchase.\n6. **Handle Objections**: Address concerns confidently with solutions, not excuses.\n7. **Create Urgency**: When appropriate, mention limited availability or special offers.\n8. **Close the Deal**: When you have enough information, propose the next concrete step (confirm booking, send contract, schedule visit).\n\nCRITICAL: Pay attention to what the customer has already told you. Acknowledge their previous messages and move the conversation forward - don\'t repeat questions. Keep responses concise and action-oriented.', help_text='Define AI personality and behavior'),
        ),
    ]
