# Generated by Django 5.2.11 on 2026-02-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_enable_auto_status_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='check_in_date',
            field=models.DateField(blank=True, help_text='Guest check-in date', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='check_out_date',
            field=models.DateField(blank=True, help_text='Guest check-out date', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='guest_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of guests', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='meal_plan',
            field=models.CharField(blank=True, choices=[('none', 'No meal plan'), ('breakfast', 'Breakfast only'), ('lunch', 'Lunch only'), ('dinner', 'Dinner only'), ('half_board_bl', 'Half-board: Breakfast + Lunch'), ('half_board_bd', 'Half-board: Breakfast + Dinner'), ('full_board', 'Full board')], help_text='Meal plan preference', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='room_type_preference',
            field=models.CharField(blank=True, help_text='Preferred room type, e.g. Deluxe Balcony', max_length=200),
        ),
    ]
