# Generated by Django 5.2.11 on 2026-02-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_lead_check_in_date_lead_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_steps',
            field=models.TextField(blank=True, help_text='Planned next actions for this lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='problem_description',
            field=models.TextField(blank=True, help_text='Summary of the lead / what they are looking for'),
        ),
    ]
