# Generated by Django 5.2.11 on 2026-03-05 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_lead_next_steps_alter_lead_problem_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeDocument',
        ),
        migrations.DeleteModel(
            name='KnowledgeEntry',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='use_knowledge_base',
        ),
    ]
