# Generated by Django 5.2.11 on 2026-03-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0038_remove_knowledge_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='instagram_intent_tier',
            field=models.CharField(blank=True, choices=[('booking_intent', 'Booking Intent'), ('soft_interest', 'Soft Interest'), ('not_relevant', 'Not Relevant')], help_text='Instagram DM intent classification (booking_intent / soft_interest / not_relevant)', max_length=20, null=True),
        ),
    ]
