# Generated by Django 5.2.11 on 2026-03-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0041_backfill_conversation_summaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramOAuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(help_text='Meta App ID', max_length=100)),
                ('app_secret', models.CharField(help_text='Meta App Secret', max_length=200)),
                ('access_token', models.CharField(blank=True, help_text='Long-lived User Access Token', max_length=500)),
                ('instagram_account_id', models.CharField(blank=True, help_text='Instagram Business Account ID', max_length=100)),
                ('page_id', models.CharField(blank=True, help_text='Facebook Page ID', max_length=100)),
                ('account_name', models.CharField(blank=True, help_text='Instagram account username', max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500)),
                ('token_expiry', models.DateTimeField(blank=True, help_text='Expiry of the long-lived token', null=True)),
                ('activated', models.BooleanField(default=False, help_text='Whether this config is active for incoming webhooks')),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram OAuth Configuration',
                'verbose_name_plural': 'Instagram OAuth Configuration',
            },
        ),
    ]
