# Generated by Django 5.2.11 on 2026-03-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0042_instagramoauthconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(help_text='Long-lived User Access Token (60 days)', max_length=500)),
                ('token_expiry', models.DateTimeField(blank=True, help_text='Expiry datetime of the long-lived token', null=True)),
                ('instagram_user_id', models.CharField(help_text='Instagram user ID returned by /me', max_length=100)),
                ('instagram_username', models.CharField(blank=True, help_text='Instagram username', max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Connection',
                'verbose_name_plural': 'Instagram Connection',
            },
        ),
        migrations.DeleteModel(
            name='InstagramConfig',
        ),
        migrations.DeleteModel(
            name='InstagramOAuthConfig',
        ),
    ]
