# Generated by Django 5.2.11 on 2026-03-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0044_instagramappconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramconnection',
            name='access_token',
            field=models.TextField(help_text='Long-lived User Access Token (60 days)'),
        ),
    ]
