# Generated by Django 5.2.11 on 2026-03-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0045_alter_instagramconnection_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramconnection',
            name='profile_picture_url',
            field=models.TextField(blank=True),
        ),
    ]
