# Generated by Django 5.2.11 on 2026-03-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0046_alter_instagramconnection_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconnection',
            name='webhook_subscribed',
            field=models.BooleanField(default=False, help_text='Whether POST /me/subscribed_apps has been called to activate DM delivery'),
        ),
    ]
