# Generated by Django 5.2.11 on 2026-03-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0047_instagramconnection_webhook_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Token expiry (null = non-expiring)', null=True),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='waba_id',
            field=models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='webhook_subscribed',
            field=models.BooleanField(default=False, help_text='Whether WABA is subscribed to webhook events'),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='access_token',
            field=models.TextField(help_text='WhatsApp Cloud API Access Token'),
        ),
    ]
