# Generated by Django 5.2.11 on 2026-03-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0048_whatsappconfig_token_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, default='1274437444500708', help_text='Meta App ID (defaults to built-in app)', max_length=100)),
                ('app_secret', models.CharField(blank=True, help_text='Meta App Secret — required for OAuth', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp App Config',
                'verbose_name_plural': 'WhatsApp App Config',
            },
        ),
    ]
