# Generated by Django 5.2.11 on 2026-03-16 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0049_whatsappappconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='company_name',
        ),
    ]
