# Generated by Django 5.2.11 on 2026-03-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0050_remove_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconnection',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, help_text='Instagram Business Account ID as it appears in webhook entry.id (set on first webhook receipt)', max_length=100),
        ),
        migrations.AlterField(
            model_name='instagramconnection',
            name='instagram_user_id',
            field=models.CharField(help_text='Instagram user ID returned by /me (app-scoped)', max_length=100),
        ),
    ]
