# Generated by Django 5.2.11 on 2026-03-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0051_instagramconnection_instagram_business_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether this inbound message has been read by staff'),
        ),
    ]
