# Generated by Django 5.2.11 on 2026-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0053_mark_existing_inbound_activities_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_paused',
            field=models.BooleanField(default=False, help_text='AI responses paused — manager has taken over the conversation'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='echo_origin',
            field=models.CharField(blank=True, choices=[('crm', 'CRM (sent via dashboard)'), ('instagram_app', 'Native Instagram app')], help_text='For Instagram sent activities: crm = sent from dashboard, instagram_app = sent via native app', max_length=20, null=True),
        ),
    ]
