# Generated by Django 5.2.11 on 2026-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0054_lead_ai_paused_leadactivity_echo_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='agent_context',
            field=models.JSONField(blank=True, default=dict, help_text='Shared context store for multi-agent routing (current_agent, booking_step, collected, etc.)'),
        ),
    ]
