# Generated by Django 5.2.11 on 2026-04-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0055_lead_agent_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_paused_at',
            field=models.DateTimeField(blank=True, help_text='When AI was paused', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ai_paused_by',
            field=models.CharField(blank=True, help_text='Name of user who paused AI', max_length=255),
        ),
    ]
