# Generated by Django 5.2.11 on 2026-04-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0056_lead_ai_paused_at_lead_ai_paused_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='verify_token',
            field=models.CharField(blank=True, help_text='Webhook verify token — paste into Meta App Dashboard', max_length=100),
        ),
    ]
