# Generated by Django 5.2.14 on 2026-05-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0058_aiconfig_organization_customer_organization_and_more'),
        ('organizations', '0004_organization_deleted_at_organization_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramappconfig',
            name='app_id',
            field=models.CharField(blank=True, default='', help_text='Meta App ID (defaults to built-in app)', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='instagram_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Instagram user ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='telegram_chat_id',
            field=models.CharField(blank=True, db_index=True, help_text='Telegram chat ID for direct messaging', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='whatsapp_phone',
            field=models.CharField(blank=True, db_index=True, help_text='WhatsApp phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='segment',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappappconfig',
            name='app_id',
            field=models.CharField(blank=True, default='', help_text='Meta App ID (defaults to built-in app)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('organization', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('organization', 'key')},
        ),
    ]
