# Generated by Django 5.2.11 on 2026-03-13 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0038_remove_knowledge_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFlowMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('freeform', 'Freeform'), ('flow_guided', 'Flow-guided')], default='freeform', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Flow Mode',
                'verbose_name_plural': 'AI Flow Mode',
            },
        ),
        migrations.CreateModel(
            name='ConversationFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('entry', 'Entry'), ('normal', 'Normal'), ('escalation', 'Escalation')], default='normal', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message_template', models.TextField(help_text='Message template with {placeholder} support')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flows.conversationflow')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_label', models.CharField(blank=True, max_length=255)),
                ('condition_keywords', models.TextField(blank=True, help_text='Comma-separated keywords that trigger this path')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='flows.conversationflow')),
                ('source_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='flows.flowcard')),
                ('target_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='flows.flowcard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadFlowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('is_escalated', models.BooleanField(default=False)),
                ('collected_data', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.flowcard')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.conversationflow')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_state', to='leads.lead')),
            ],
        ),
    ]
