# Generated by Django 5.2.11 on 2026-03-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0003_seed_ai_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowcard',
            name='message_template',
            field=models.TextField(blank=True, default='', help_text='Message template with {placeholder} support'),
        ),
    ]
