# Generated by Django 5.2.11 on 2026-03-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0006_aimodelconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTransferConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='telegram', max_length=20)),
                ('recipient_id', models.CharField(blank=True, max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manager Transfer Config',
                'verbose_name_plural': 'Manager Transfer Config',
            },
        ),
    ]
