# Generated by Django 5.2.11 on 2026-03-16 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0008_seed_transfer_tool'),
        ('hotel_info', '0016_roompricing_guest_type_alter_roomcombinationnote_combination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcard',
            name='playbook',
            field=models.ForeignKey(blank=True, help_text='Optional playbook to inject into AI context when this card is active', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_cards', to='hotel_info.playbook'),
        ),
    ]
