# Generated by Django 5.2.11 on 2026-03-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0009_flowcard_playbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='managertransferconfig',
            name='notification_template',
            field=models.TextField(blank=True, help_text='Custom notification message template. Leave blank to use the default. Available variables: {reason}, {guest_name}, {guest_phone}, {guest_email}, {platform}, {checkin_date}, {checkout_date}, {nights}, {guest_count}, {room_description}, {meal_plan}, {price_per_night}, {total_price}, {notes}, {contact_id}'),
        ),
    ]
