# Generated by Django 5.2.11 on 2026-03-22 22:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0015_add_family_room_tool'),
        ('hotel_info', '0017_remove_ai_style_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('booking', 'Booking Agent'), ('cs', 'Customer Service Agent'), ('consultant', 'Consultant Agent'), ('router', 'Intent Router')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(blank=True)),
                ('tools', models.JSONField(blank=True, default=list, help_text='List of tool names available to this agent')),
                ('is_editable', models.BooleanField(default=True, help_text='Intent Router is not editable')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playbooks', models.ManyToManyField(blank=True, related_name='agent_configs', to='hotel_info.playbook')),
            ],
            options={
                'verbose_name': 'Agent Config',
                'verbose_name_plural': 'Agent Configs',
                'ordering': ['created_at'],
            },
        ),
    ]
