# Generated by Django 5.2.11 on 2026-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roompricing',
            options={'ordering': ['room_type', 'meal_plan']},
        ),
        migrations.RemoveField(
            model_name='roompricing',
            name='duration',
        ),
        migrations.AddField(
            model_name='roompricing',
            name='meal_plan',
            field=models.CharField(choices=[('standard', 'Standard (room only)'), ('breakfast', 'Breakfast included'), ('lunch_dinner', 'Lunch or Dinner included'), ('full_board', 'Breakfast, Lunch and Dinner included')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='roompricing',
            name='season_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roompricing',
            name='season_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roompricing',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('comfort', 'Comfort'), ('family_1', 'Family (1 room)'), ('family_2', 'Family (2 rooms)')], max_length=20),
        ),
    ]
