# Generated by Django 5.2.11 on 2026-03-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0002_alter_roompricing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roompricing',
            options={'ordering': ['room_type', 'persons', 'is_weekend', 'meal_plan']},
        ),
        migrations.AddField(
            model_name='roompricing',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roompricing',
            name='persons',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
