# Generated by Django 5.2.11 on 2026-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0004_roompricing_day_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIStyleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(choices=[('attentive_host', 'Attentive Host'), ('concierge', 'Concierge'), ('sales_rep', 'Sales Rep'), ('custom', 'Custom')], default='attentive_host', max_length=20)),
                ('custom_persona', models.TextField(blank=True, help_text='Custom personality description (used when persona=custom)')),
                ('tone', models.CharField(choices=[('warm', 'Warm'), ('formal', 'Formal'), ('casual', 'Casual'), ('direct', 'Direct')], default='warm', max_length=10)),
                ('emoji_use', models.CharField(choices=[('none', 'None'), ('minimal', 'Minimal'), ('normal', 'Normal')], default='minimal', max_length=10)),
                ('response_length', models.CharField(choices=[('brief', 'Brief'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], default='balanced', max_length=10)),
                ('upselling', models.CharField(choices=[('off', 'Off'), ('subtle', 'Subtle'), ('active', 'Active')], default='subtle', max_length=10)),
                ('follow_ups', models.CharField(choices=[('off', 'Off'), ('gentle', 'Gentle'), ('persistent', 'Persistent')], default='gentle', max_length=12)),
                ('lang_russian', models.BooleanField(default=True)),
                ('lang_kyrgyz', models.BooleanField(default=True)),
                ('lang_english', models.BooleanField(default=True)),
                ('lang_auto_detect', models.BooleanField(default=False)),
                ('example_conversations', models.TextField(blank=True, help_text='Example conversations showing the AI how to talk. Paste real WhatsApp/Telegram exchanges.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Style Configuration',
                'verbose_name_plural': 'AI Style Configuration',
            },
        ),
    ]
