# Generated by Django 5.2.11 on 2026-03-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0005_aistyleconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('escalate_when', models.CharField(blank=True, help_text='Describe when this person should be contacted.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Handover Contact',
                'verbose_name_plural': 'Handover Contacts',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HotelFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hotel FAQ',
                'verbose_name_plural': 'Hotel FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HotelPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Animals / Pets, Parking, Smoking', max_length=100)),
                ('emoji', models.CharField(blank=True, help_text='Optional emoji prefix', max_length=10)),
                ('value', models.CharField(help_text='e.g. Allowed, Paid parking available, Not allowed', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional detail the AI can share when guests ask follow-up questions.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Hotel Policy',
                'verbose_name_plural': 'Hotel Policies',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HotelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, help_text='Short intro the AI uses when guests ask about the hotel.')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('directions', models.TextField(blank=True, help_text='Turn-by-turn directions the AI shares when guests ask how to get here.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Profile',
                'verbose_name_plural': 'Hotel Profile',
            },
        ),
        migrations.CreateModel(
            name='HotelProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='hotel_info.hotelprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
