# Generated by Django 5.2.11 on 2026-03-05 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0006_handovercontact_hotelfaq_hotelpolicy_hotelprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_description', models.TextField(blank=True, help_text='Describe in plain language when this playbook should activate.')),
                ('instructions', models.TextField(blank=True, help_text='How the AI should respond in this scenario.')),
                ('content', models.TextField(blank=True, help_text='Additional facts, tables, or examples (markdown supported).')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
