# Generated by Django 5.2.11 on 2026-03-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0007_playbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomPricing',
        ),
    ]
