# Generated by Django 5.2.11 on 2026-03-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0008_remove_roompricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusection',
            name='plan',
        ),
        migrations.DeleteModel(
            name='MenuDish',
        ),
        migrations.DeleteModel(
            name='MenuPlan',
        ),
        migrations.DeleteModel(
            name='MenuSection',
        ),
    ]
