# Generated by Django 5.2.11 on 2026-03-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0009_remove_menu_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria_nomera', models.CharField(help_text='Room category, e.g. Стандарт, Комфорт', max_length=100)),
                ('kolichestvo_chelovek', models.IntegerField(help_text='Number of guests (1–4)')),
                ('deystvitelno_s', models.DateField(blank=True, help_text='Valid from date', null=True)),
                ('deystvitelno_do', models.DateField(blank=True, help_text='Valid until date', null=True)),
                ('dni_nedeli', models.JSONField(blank=True, default=list, help_text='List of Russian weekday names')),
                ('standartny_tarif', models.DecimalField(blank=True, decimal_places=0, help_text='Base rate KGS', max_digits=10, null=True)),
                ('s_zavtrakom', models.DecimalField(blank=True, decimal_places=0, help_text='With breakfast KGS', max_digits=10, null=True)),
                ('polupansion', models.DecimalField(blank=True, decimal_places=0, help_text='Half board KGS', max_digits=10, null=True)),
                ('polny_pansion', models.DecimalField(blank=True, decimal_places=0, help_text='Full board KGS', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Pricing',
                'verbose_name_plural': 'Room Pricing',
                'ordering': ['kategoria_nomera', 'kolichestvo_chelovek', 'id'],
            },
        ),
    ]
