# Generated by Django 5.2.11 on 2026-03-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0010_roompricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roompricing',
            options={'ordering': ['id'], 'verbose_name': 'Room Pricing', 'verbose_name_plural': 'Room Pricing'},
        ),
    ]
