# Generated by Django 5.2.11 on 2026-03-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0011_alter_roompricing_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCombinationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_count', models.IntegerField(help_text='Number of guests (1–10)')),
                ('combination_index', models.IntegerField(help_text='0 = Основной, 1+ = Альтернатива')),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Combination Note',
                'verbose_name_plural': 'Room Combination Notes',
                'ordering': ['guest_count', 'combination_index'],
                'unique_together': {('guest_count', 'combination_index')},
            },
        ),
    ]
