# Generated by Django 5.2.11 on 2026-03-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0012_roomcombinationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcombinationnote',
            name='combination_type',
            field=models.CharField(blank=True, choices=[('Основной', 'Основной'), ('Альтернатива', 'Альтернатива')], help_text='Manually set type; null = auto-assigned from pricing', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomcombinationnote',
            name='combination_index',
            field=models.IntegerField(help_text='0-based index within the guest count group'),
        ),
    ]
