# Generated by Django 5.2.11 on 2026-03-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0013_roomcombinationnote_combination_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcombinationnote',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True for user-added combinations; False for auto-generated ones'),
        ),
        migrations.AddField(
            model_name='roomcombinationnote',
            name='rooms',
            field=models.JSONField(blank=True, default=None, help_text='List of room type strings for custom combinations', null=True),
        ),
    ]
