# Generated by Django 5.2.11 on 2026-03-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0016_roompricing_guest_type_alter_roomcombinationnote_combination_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIStyleConfig',
        ),
    ]
