# Generated by Django 5.2.11 on 2026-04-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_info', '0019_assign_org_to_orphaned_playbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiry. Playbook stops being injected into AI once this date/time passes.', null=True),
        ),
    ]
