/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuperAdminRouteRouteImport } from './routes/super-admin/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as SuperAdminOrganizationsRouteImport } from './routes/super-admin/organizations'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppHotelDetailsRouteImport } from './routes/_app/hotel-details'
import { Route as AppFlowsRouteImport } from './routes/_app/flows'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCommunicationsRouteImport } from './routes/_app/communications'
import { Route as AppAuditLogsRouteImport } from './routes/_app/audit-logs'
import { Route as AppPortalRouteRouteImport } from './routes/_app/portal/route'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/_app/leads/$leadId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers/$customerId'
import { Route as AppPortalUsersIndexRouteImport } from './routes/_app/portal/users/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRouteRoute = SuperAdminRouteRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminOrganizationsRoute = SuperAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHotelDetailsRoute = AppHotelDetailsRouteImport.update({
  id: '/hotel-details',
  path: '/hotel-details',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFlowsRoute = AppFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCommunicationsRoute = AppCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPortalRouteRoute = AppPortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRoute,
} as any)
const AppPortalUsersIndexRoute = AppPortalUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppPortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/portal': typeof AppPortalRouteRouteWithChildren
  '/audit-logs': typeof AppAuditLogsRoute
  '/communications': typeof AppCommunicationsRoute
  '/customers': typeof AppCustomersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/flows': typeof AppFlowsRoute
  '/hotel-details': typeof AppHotelDetailsRoute
  '/pipeline': typeof AppPipelineRoute
  '/settings': typeof AppSettingsRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/contacts': typeof AppContactsIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/portal/users': typeof AppPortalUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/portal': typeof AppPortalRouteRouteWithChildren
  '/audit-logs': typeof AppAuditLogsRoute
  '/communications': typeof AppCommunicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/flows': typeof AppFlowsRoute
  '/hotel-details': typeof AppHotelDetailsRoute
  '/pipeline': typeof AppPipelineRoute
  '/settings': typeof AppSettingsRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/contacts': typeof AppContactsIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/portal/users': typeof AppPortalUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/portal': typeof AppPortalRouteRouteWithChildren
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/communications': typeof AppCommunicationsRoute
  '/_app/customers': typeof AppCustomersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/flows': typeof AppFlowsRoute
  '/_app/hotel-details': typeof AppHotelDetailsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/settings': typeof AppSettingsRoute
  '/super-admin/organizations': typeof SuperAdminOrganizationsRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/portal/users/': typeof AppPortalUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/super-admin'
    | '/login'
    | '/register'
    | '/portal'
    | '/audit-logs'
    | '/communications'
    | '/customers'
    | '/dashboard'
    | '/flows'
    | '/hotel-details'
    | '/pipeline'
    | '/settings'
    | '/super-admin/organizations'
    | '/super-admin/'
    | '/customers/$customerId'
    | '/leads/$leadId'
    | '/contacts'
    | '/customers/'
    | '/leads'
    | '/portal/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/portal'
    | '/audit-logs'
    | '/communications'
    | '/dashboard'
    | '/flows'
    | '/hotel-details'
    | '/pipeline'
    | '/settings'
    | '/super-admin/organizations'
    | '/super-admin'
    | '/customers/$customerId'
    | '/leads/$leadId'
    | '/contacts'
    | '/customers'
    | '/leads'
    | '/portal/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/super-admin'
    | '/login'
    | '/register'
    | '/_app/portal'
    | '/_app/audit-logs'
    | '/_app/communications'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/flows'
    | '/_app/hotel-details'
    | '/_app/pipeline'
    | '/_app/settings'
    | '/super-admin/organizations'
    | '/super-admin/'
    | '/_app/customers/$customerId'
    | '/_app/leads/$leadId'
    | '/_app/contacts/'
    | '/_app/customers/'
    | '/_app/leads/'
    | '/_app/portal/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SuperAdminRouteRoute: typeof SuperAdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/organizations': {
      id: '/super-admin/organizations'
      path: '/organizations'
      fullPath: '/super-admin/organizations'
      preLoaderRoute: typeof SuperAdminOrganizationsRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/hotel-details': {
      id: '/_app/hotel-details'
      path: '/hotel-details'
      fullPath: '/hotel-details'
      preLoaderRoute: typeof AppHotelDetailsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/flows': {
      id: '/_app/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AppFlowsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/communications': {
      id: '/_app/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AppCommunicationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/portal': {
      id: '/_app/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AppPortalRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/leads/$leadId': {
      id: '/_app/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRoute
    }
    '/_app/portal/users/': {
      id: '/_app/portal/users/'
      path: '/users'
      fullPath: '/portal/users'
      preLoaderRoute: typeof AppPortalUsersIndexRouteImport
      parentRoute: typeof AppPortalRouteRoute
    }
  }
}

interface AppPortalRouteRouteChildren {
  AppPortalUsersIndexRoute: typeof AppPortalUsersIndexRoute
}

const AppPortalRouteRouteChildren: AppPortalRouteRouteChildren = {
  AppPortalUsersIndexRoute: AppPortalUsersIndexRoute,
}

const AppPortalRouteRouteWithChildren = AppPortalRouteRoute._addFileChildren(
  AppPortalRouteRouteChildren,
)

interface AppCustomersRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteChildren: AppCustomersRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteWithChildren = AppCustomersRoute._addFileChildren(
  AppCustomersRouteChildren,
)

interface AppRouteRouteChildren {
  AppPortalRouteRoute: typeof AppPortalRouteRouteWithChildren
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppCommunicationsRoute: typeof AppCommunicationsRoute
  AppCustomersRoute: typeof AppCustomersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppFlowsRoute: typeof AppFlowsRoute
  AppHotelDetailsRoute: typeof AppHotelDetailsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPortalRouteRoute: AppPortalRouteRouteWithChildren,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppCommunicationsRoute: AppCommunicationsRoute,
  AppCustomersRoute: AppCustomersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppFlowsRoute: AppFlowsRoute,
  AppHotelDetailsRoute: AppHotelDetailsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SuperAdminRouteRouteChildren {
  SuperAdminOrganizationsRoute: typeof SuperAdminOrganizationsRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteRouteChildren: SuperAdminRouteRouteChildren = {
  SuperAdminOrganizationsRoute: SuperAdminOrganizationsRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteRouteWithChildren = SuperAdminRouteRoute._addFileChildren(
  SuperAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SuperAdminRouteRoute: SuperAdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
