# Generated by Django 5.2.11 on 2026-03-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='AI uses this to decide when to send this media to leads')),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tag strings')),
                ('category', models.CharField(choices=[('rooms', 'Guest Rooms'), ('cafeteria', 'Cafeteria & Dining'), ('pool', 'Pool'), ('spa', 'Spa & Wellness'), ('conference', 'Conference & Events'), ('exterior', 'Exterior & Views'), ('lobby', 'Lobby & Common Areas'), ('other', 'Other')], default='other', max_length=50)),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], default='photo', max_length=20)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (photo, video, document)', null=True, upload_to='hotel_media/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)')),
                ('ai_send_count', models.PositiveIntegerField(default=0, help_text='Number of times the AI agent has sent this item to leads')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Media Item',
                'verbose_name_plural': 'Hotel Media Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
