# Generated by Django 5.2.11 on 2026-03-02 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMediaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='hotel_media/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotel_media.hotelmediaitem')),
            ],
            options={
                'verbose_name': 'Hotel Media Photo',
                'verbose_name_plural': 'Hotel Media Photos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
