# Generated by Django 5.2.11 on 2026-03-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_media', '0002_hotelmediaphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmediaitem',
            name='room_category',
            field=models.CharField(blank=True, choices=[('standard_queen', 'Standard Queen'), ('standard_twin', 'Standard Twin'), ('comfort', 'Comfort'), ('family', 'Family'), ('other', 'Other')], help_text='Room type for AI photo tool (only for Rooms category)', max_length=50, null=True),
        ),
    ]
