# Generated by Django 5.2.11 on 2026-04-14 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_media', '0003_hotelmediaitem_room_category'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmediaitem',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
    ]
