# Generated by Django 5.2.11 on 2026-02-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin / Manager'), ('support', 'Support'), ('tax_accountant', 'Tax Accountant')], default='support', max_length=50),
        ),
    ]
